import { Interest } from "./types";

export const interestsData: Interest[] = [
  {
    id: "gaming",
    name: "Oyunlar",
    nameEn: "Gaming",
    icon: "",
    color: "bg-purple-500",
    userCount: 12548,
    subInterests: [
      {
        id: "lol",
        name: "League of Legends",
        nameEn: "League of Legends",
        logo: "https://www.pngegg.com/en/png-iafor",
        userCount: 856,
      },
      {
        id: "cs2",
        name: "Counter-Strike 2",
        nameEn: "Counter-Strike 2",
        logo: "https://seeklogo.com/vector-logo/534313/counter-strike-2",
        userCount: 723,
      },
      {
        id: "valorant",
        name: "Valorant",
        nameEn: "Valorant",
        logo: "https://www.vhv.rs/viewpic/hoxRTii_valorant-logo-png-transparent-png/",
        userCount: 692,
      },
      {
        id: "dota2",
        name: "Dota 2",
        nameEn: "Dota 2",
        logo: "https://www.citypng.com/photo/5504/hd-dota-2-official-logo-png",
        userCount: 445,
      },
      {
        id: "mhwilds",
        name: "Monster Hunter: Wilds",
        nameEn: "Monster Hunter: Wilds",
        userCount: 234,
      },
      {
        id: "eldenring",
        name: "Elden Ring: Shadow of the Erdtree DLC",
        nameEn: "Elden Ring: Shadow of the Erdtree DLC",
        userCount: 567,
      },
      {
        id: "pubg",
        name: "PUBG: Battlegrounds & Mobile",
        nameEn: "PUBG: Battlegrounds & Mobile",
        userCount: 1234,
      },
      {
        id: "gta",
        name: "GTA V / GTA Online",
        nameEn: "GTA V / GTA Online",
        userCount: 987,
      },
      {
        id: "apex",
        name: "Apex Legends",
        nameEn: "Apex Legends",
        userCount: 654,
      },
      {
        id: "warthunder",
        name: "War Thunder",
        nameEn: "War Thunder",
        userCount: 321,
      },
      {
        id: "rust",
        name: "Rust",
        nameEn: "Rust",
        userCount: 445,
      },
      {
        id: "ark",
        name: "Ark: Survival",
        nameEn: "Ark: Survival",
        userCount: 289,
      },
      {
        id: "roblox",
        name: "Roblox",
        nameEn: "Roblox",
        userCount: 1567,
      },
      {
        id: "candycrush",
        name: "Candy Crush Saga",
        nameEn: "Candy Crush Saga",
        userCount: 2134,
      },
      {
        id: "royalmatch",
        name: "Royal Match",
        nameEn: "Royal Match",
        userCount: 1876,
      },
      {
        id: "freefire",
        name: "Free Fire",
        nameEn: "Free Fire",
        userCount: 1432,
      },
      {
        id: "honkaistarrail",
        name: "Honkai: Star Rail",
        nameEn: "Honkai: Star Rail",
        userCount: 567,
      },
      {
        id: "brawlstars",
        name: "Brawl Stars",
        nameEn: "Brawl Stars",
        userCount: 1234,
      },
      {
        id: "clashofclans",
        name: "Clash of Clans",
        nameEn: "Clash of Clans",
        userCount: 1987,
      },
    ],
  },
];
